name: Sentry Notify Release

on:
  push:
    tags:
      - "*"

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create a Sentry.io release
        uses: tclindner/sentry-releases-action@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: nimiq
          SENTRY_PROJECT: wallet
        with:
          tagName: ${{ github.ref }}
          environment: test
          releaseNamePrefix: wallet-
